version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
  es:
    build:
      context: .
      dockerfile: ./es/Dockerfile
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  # kibana:
  #   image: kibana:4
  #   environment:
  #     - ELASTICSEARCH_URL=http://es:9200
  #   ports:
  #     - "5601:5601"
  redis:
    image: redis:2.8.23
    volumes:
      - redisdata:/data
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    command: /usr/local/bin/docker-bootstrap
    environment:
      - ELASTICSEARCH_URL=es:9200
      - REDIS_URL=redis://redis:6379
      - LETTER_OPENER_DELIVERY_METHOD=letter_opener_web
    volumes:
      - ./src:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysqldata:
    external: false
  esdata:
    external: false
  redisdata:
    external: false
