version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
  es:
    build:
      context: .
      dockerfile: ./es/Dockerfile
    volumes:
      - esdata:/usr/share/elasticsearch/data
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - ELASTICSEARCH_URL=es:9200
      - LETTER_OPENER_DELIVERY_METHOD=letter_opener_web
    volumes:
      - ./src:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysqldata:
    external: false
  esdata:
    external: false
